[project]
name = "05-space-invaders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MMarquezRoldan", email = "miguelmroldan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
05-space-invaders = "05_space_invaders:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []
unfixable = ["F841", "F401"]
